---
api-version: 1.16
commands:
  ab:
    usage: /ab
  go:
    usage: /go
  ability:
    usage: /ability
  manhunt:
    usage: /manhunt
  run:
    usage: /run
  des:
    usage: /des
main: hypixel.hypixel.Hypixel
name: Hypixel
version: "${project.version}"