---
api-version: 1.16
commands:
  ab:
    usage: /ab
  go:
    usage: /go
  ability:
    usage: /ability
  manhunt:
    usage: /manhunt
  ran:
    usage: /ran
main: hypixel.hypixel.Hypixel
name: Hypixel
version: "${project.version}"